title: Spelldawn
description: An asymmetric digital trading card game
url: "https://spelldawn.com"

remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-gist

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
