title: Spelldawn
description: An asymmetric digital trading card game
url: "https://spelldawn.com"

remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-gist

exclude:
  - package-lock.json
  - README.md
  - LICENSE
  - out
  - serve.sh
  - .sass-cache/
  - package.json
  - node_modules/
  - tsconfig.json
  - rollup.config.js
  - .jekyll-cache/
  - src/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
